@startuml
start

:Запуск приложения;
:Показать экран выбора роли;

partition RoleSelection {
  :Ожидание выбора роли;
  if (Нажата кнопка "Организатор"?) then (да)
    :enterFlag = 'o';
  else (нет)
    if (Нажата кнопка "Участник"?) then (да)
      :enterFlag = 'm';
    else (нет)
      stop
    endif
  endif
  :Загрузка страницы регистрации;
}

partition Registration {
  :Пользователь вводит данные;
  if (Нажата кнопка "Войти"?) then (да)
    :Проверка логина и пароля;
    if (Успешно?) then (да)
      :Переход в меню;
    else (нет)
      :Показать ошибку входа;
      -> :Пользователь вводит данные;
    endif
  else if (Нажата кнопка "Зарегистрироваться"?) then (да)
    :Проверка введённых данных;
    if (Данные корректны?) then (да)
      :Сохранение нового пользователя;
      :Переход в меню;
    else (нет)
      :Показать ошибку регистрации;
      -> :Пользователь вводит данные;
    endif
  else (нет)
    stop
  endif
}

partition Menu {
  :Загрузить список мероприятий;
  :Отобразить мероприятия;

  if (enterFlag == 'o') then (Организатор)
    fork
      :Создать мероприятие;
      if (Пользователь нажал "Создать"?) then (да)
        :Открыть окно создания;
        if (Данные валидны?) then (да)
          :Сохранить мероприятие в БД;
          :Обновить список;
        else (нет)
          :Показать ошибку;
        endif
      endif
    fork again
      :Удалить мероприятие;
      if (Выбрано мероприятие и нажата кнопка "Удалить"?) then (да)
        :Удалить из БД;
        :Обновить список;
      else (нет)
        :Показать сообщение "Выберите мероприятие";
      endif
    fork again
      :Открыть посещаемость;
      if (Выбрано мероприятие и нажата кнопка "Открыть посещаемость"?) then (да)
        :Открыть окно посещаемости;
        :Отметить явку участников;
      else (нет)
        :Показать сообщение "Выберите мероприятие";
      endif
    end fork
  else (Участник)
    :Подать заявку на участие;
    if (Выбрано мероприятие и нажата кнопка "Подать заявку"?) then (да)
      :Добавить заявку в БД;
      :Показать подтверждение;
    else (нет)
      :Показать сообщение "Выберите мероприятие";
    endif
  endif

  :Обновить список по нажатию кнопки "Обновить";
}

stop
@enduml